// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: menu.sql

package db

import (
	"context"
	"database/sql"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu (
  business_id, item_name, item_description, price, image_url
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING menu_id, business_id, item_name, item_description, price, image_url
`

type CreateMenuItemParams struct {
	BusinessID      sql.NullInt32  `json:"business_id"`
	ItemName        sql.NullString `json:"item_name"`
	ItemDescription sql.NullString `json:"item_description"`
	Price           sql.NullString `json:"price"`
	ImageUrl        sql.NullString `json:"image_url"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (Menu, error) {
	row := q.queryRow(ctx, q.createMenuItemStmt, createMenuItem,
		arg.BusinessID,
		arg.ItemName,
		arg.ItemDescription,
		arg.Price,
		arg.ImageUrl,
	)
	var i Menu
	err := row.Scan(
		&i.MenuID,
		&i.BusinessID,
		&i.ItemName,
		&i.ItemDescription,
		&i.Price,
		&i.ImageUrl,
	)
	return i, err
}
