// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Business struct {
	BusinessID     int32          `json:"business_id"`
	BusinessName   sql.NullString `json:"business_name"`
	BusinessOwner  sql.NullString `json:"business_owner"`
	AddressStreet  sql.NullString `json:"address_street"`
	AddressCity    sql.NullString `json:"address_city"`
	AddressState   sql.NullString `json:"address_state"`
	AddressZipcode sql.NullString `json:"address_zipcode"`
	BusinessHours  []int32        `json:"business_hours"`
	BusinessDays   []int32        `json:"business_days"`
	Seating        sql.NullInt32  `json:"seating"`
	BusinessType   sql.NullString `json:"business_type"`
	IsActive       sql.NullBool   `json:"is_active"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type Menu struct {
	MenuID          int32          `json:"menu_id"`
	BusinessID      sql.NullInt32  `json:"business_id"`
	ItemName        sql.NullString `json:"item_name"`
	ItemDescription sql.NullString `json:"item_description"`
	Price           sql.NullString `json:"price"`
	ImageUrl        sql.NullString `json:"image_url"`
}

type Reservation struct {
	ReservationsID   int32          `json:"reservations_id"`
	BusinessID       sql.NullInt32  `json:"business_id"`
	GuestName        sql.NullString `json:"guest_name"`
	ReservationDate  sql.NullString `json:"reservation_date"`
	ReservationHours sql.NullInt16  `json:"reservation_hours"`
	Guests           sql.NullInt16  `json:"guests"`
	DiningRoom       sql.NullBool   `json:"dining_room"`
	Paid             sql.NullBool   `json:"paid"`
}
